// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

Future<void> initializeFirebase() async {
  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp();
  }
}
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3CukxeX4zWxuCVvpTCwYbDn6oMPlGtrE',
    appId: '1:451156264454:web:418da3cad7fb822fb6a587',
    messagingSenderId: '451156264454',
    projectId: 'out-f555c',
    authDomain: 'out-f555c.firebaseapp.com',
    storageBucket: 'out-f555c.firebasestorage.app',
    measurementId: 'G-G6KPQDJPJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOrmQJqTcQLA_zxrW3yqW9T0UzAZV6NA',
    appId: '1:451156264454:android:f168201647b4d5edb6a587',
    messagingSenderId: '451156264454',
    projectId: 'out-f555c',
    storageBucket: 'out-f555c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9v7_S1_Pd1jEJmyy75ydZsmx6Jc20Mtw',
    appId: '1:451156264454:ios:c4ae910f541aedd2b6a587',
    messagingSenderId: '451156264454',
    projectId: 'out-f555c',
    storageBucket: 'out-f555c.firebasestorage.app',
    iosBundleId: 'com.example.outApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9v7_S1_Pd1jEJmyy75ydZsmx6Jc20Mtw',
    appId: '1:451156264454:ios:c4ae910f541aedd2b6a587',
    messagingSenderId: '451156264454',
    projectId: 'out-f555c',
    storageBucket: 'out-f555c.firebasestorage.app',
    iosBundleId: 'com.example.outApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3CukxeX4zWxuCVvpTCwYbDn6oMPlGtrE',
    appId: '1:451156264454:web:7c4b3ce71d30c4e9b6a587',
    messagingSenderId: '451156264454',
    projectId: 'out-f555c',
    authDomain: 'out-f555c.firebaseapp.com',
    storageBucket: 'out-f555c.firebasestorage.app',
    measurementId: 'G-TEE0EKGDHR',
  );
}
